const tagLabels: Record<string, string> = {
  "data-structures": "Data Structures",
  algorithms: "Algorithms",
  networking: "Networking",
  "operating-systems": "Operating Systems",
  "distributed-systems": "Distributed Systems",
  "api-design": "API Design",
  "design-patterns": "Design Patterns",
  "system-design": "System Design",
  "object-oriented": "OOP",
  javascript: "JavaScript",
  typescript: "TypeScript",
  react: "React",
  angular: "Angular",
  vue: "Vue.js",
  css: "CSS",
  html: "HTML",
  dom: "DOM",
  performance: "Performance",
  accessibility: "Accessibility",
  testing: "Testing",
  "testing-basics": "Testing Basics",
  "testing-strategy": "Testing Strategy",
  "testing-tools": "Testing Tools",
  "testing-types": "Testing Types",
  "testing-methodology": "Testing Methodology",
  automation: "Automation",
  security: "Security",
  authentication: "Authentication",
  authorization: "Authorization",
  databases: "Databases",
  sql: "SQL",
  nosql: "NoSQL",
  mongodb: "MongoDB",
  postgresql: "PostgreSQL",
  mysql: "MySQL",
  redis: "Redis",
  caching: "Caching",
  nodejs: "Node.js",
  express: "Express.js",
  spring: "Spring Boot",
  django: "Django",
  "ci-cd": "CI/CD",
  docker: "Docker",
  kubernetes: "Kubernetes",
  cloud: "Cloud",
  aws: "AWS",
  gcp: "GCP",
  azure: "Azure",
  devops: "DevOps",
  git: "Git",
  "best-practices": "Best Practices",
  "real-time": "Real-Time",
  optimization: "Optimization",
  monitoring: "Monitoring",
  observability: "Observability",
  architecture: "Architecture",
  microservices: "Microservices",
  "event-driven": "Event-Driven",
  grpc: "gRPC",
  rest: "REST",
  graphql: "GraphQL",
  websocket: "WebSocket",
};

export function formatTagLabel(tag: string): string {
  return (
    tagLabels[tag] ||
    tag.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
  );
}
