export const categoriesData = [
  {
    name: "Software Engineer",
    slug: "software-engineer",
    description: "General software engineering concepts, OOP, system design, data structures, and algorithms.",
    icon: "💻",
    color: "text-blue-500",
    order_index: 1,
  },
  {
    name: "Frontend Engineer",
    slug: "frontend-engineer",
    description: "HTML, CSS, JavaScript, React, Angular, and browser concepts.",
    icon: "🎨",
    color: "text-sky-500",
    order_index: 2,
  },
  {
    name: "Backend Engineer",
    slug: "backend-engineer",
    description: "Server-side programming, APIs, databases, authentication, and scalability.",
    icon: "⚙️",
    color: "text-emerald-500",
    order_index: 3,
  },
  {
    name: "Fullstack Engineer",
    slug: "fullstack-engineer",
    description: "End-to-end development, frontend + backend integration, deployment, and DevOps.",
    icon: "🌐",
    color: "text-purple-500",
    order_index: 4,
  },
  {
    name: "DevOps Engineer",
    slug: "devops-engineer",
    description: "CI/CD, cloud infrastructure, containerization, monitoring, and automation.",
    icon: "🚀",
    color: "text-orange-500",
    order_index: 5,
  },
  {
    name: "QA Engineer",
    slug: "qa-engineer",
    description: "Testing methodologies, automation frameworks, bug tracking, and quality assurance.",
    icon: "🧪",
    color: "text-red-500",
    order_index: 6,
  },
];

export const questionsData: Record<string, { question: string; answer: string; difficulty: string; tags: string[]; is_top50: boolean }[]> = {
  "software-engineer": [
    {
      question: "What is the difference between an array and a linked list?",
      answer: "An array is a contiguous block of memory where elements are accessed by index in O(1) time, but insertion/deletion is O(n). A linked list consists of nodes with pointers — insertion/deletion is O(1) at known position, but access is O(n). Arrays have better cache locality; linked lists use more memory per element.",
      difficulty: "easy",
      tags: ["data-structures"],
      is_top50: true,
    },
    {
      question: "Explain the concept of Big O notation.",
      answer: "Big O notation describes the upper bound of an algorithm's time or space complexity as input size grows. It ignores constants and lower-order terms. Common complexities: O(1) constant, O(log n) logarithmic, O(n) linear, O(n log n), O(n²) quadratic, O(2ⁿ) exponential. It helps compare algorithm efficiency.",
      difficulty: "easy",
      tags: ["algorithms"],
      is_top50: true,
    },
    {
      question: "What is the difference between TCP and UDP?",
      answer: "TCP is connection-oriented, guarantees delivery, ensures ordering, and provides flow control — used for web browsing, email, file transfer. UDP is connectionless, faster, with no guarantee of delivery or ordering — used for streaming, gaming, DNS queries. TCP has higher overhead; UDP is lightweight.",
      difficulty: "medium",
      tags: ["networking"],
      is_top50: true,
    },
    {
      question: "Explain how a hash table works.",
      answer: "A hash table stores key-value pairs. A hash function maps each key to an index (bucket). Collisions are handled via chaining (linked list per bucket) or open addressing (probing). Average lookup is O(1), worst-case O(n) with many collisions. Good hash functions distribute keys uniformly.",
      difficulty: "medium",
      tags: ["data-structures"],
      is_top50: true,
    },
    {
      question: "What is the difference between processes and threads?",
      answer: "A process is an independent program with its own memory space (isolated). A thread is a lightweight unit of execution within a process, sharing memory with sibling threads. Processes are more expensive to create and switch between. Threads enable parallelism within a process but require synchronization.",
      difficulty: "medium",
      tags: ["operating-systems"],
      is_top50: true,
    },
    {
      question: "Explain the CAP theorem.",
      answer: "The CAP theorem states a distributed system can only provide two of three guarantees: Consistency (all nodes see the same data), Availability (every request gets a response), and Partition Tolerance (system works despite network failures). In practice, CP systems sacrifice availability during partitions; AP systems sacrifice consistency.",
      difficulty: "hard",
      tags: ["distributed-systems"],
      is_top50: true,
    },
    {
      question: "Describe the differences between REST and GraphQL.",
      answer: "REST uses fixed endpoints with HTTP methods; each endpoint returns a predefined data structure. GraphQL uses a single endpoint where clients specify exactly what fields they need. REST is simpler for basic CRUD; GraphQL reduces over-fetching/under-fetching. REST relies on HTTP caching; GraphQL requires custom caching.",
      difficulty: "medium",
      tags: ["api-design"],
      is_top50: true,
    },
    {
      question: "What is dependency injection and why use it?",
      answer: "Dependency injection is a design pattern where dependencies are provided (injected) to a class rather than the class creating them itself. Benefits: loose coupling, easier testing (mocking), improved maintainability, and configuration flexibility. Typically done via constructor injection or setter injection.",
      difficulty: "medium",
      tags: ["design-patterns"],
      is_top50: true,
    },
  ],
  "frontend-engineer": [
    {
      question: "What is the DOM and how does it work?",
      answer: "The DOM (Document Object Model) is a tree-like representation of an HTML document that JavaScript can manipulate. When a page loads, the browser parses HTML into DOM nodes. JavaScript can traverse, add, remove, or modify nodes, which triggers re-rendering. Virtual DOM (used by React) batches changes for performance.",
      difficulty: "easy",
      tags: ["dom", "javascript"],
      is_top50: true,
    },
    {
      question: "Explain the CSS box model.",
      answer: "The CSS box model describes how every element is rendered as a rectangular box consisting of: content (inner area), padding (space around content), border (around padding), and margin (space outside border). The `box-sizing` property controls whether width/height includes padding and border (border-box) or just content (content-box).",
      difficulty: "easy",
      tags: ["css"],
      is_top50: true,
    },
    {
      question: "What is the difference between '==' and '===' in JavaScript?",
      answer: "'==' (abstract equality) performs type coercion before comparing, so `5 == '5'` is true. '===' (strict equality) compares both value and type without coercion, so `5 === '5'` is false. Best practice: always use '===' unless you explicitly need type coercion.",
      difficulty: "easy",
      tags: ["javascript"],
      is_top50: true,
    },
    {
      question: "Explain closures in JavaScript.",
      answer: "A closure is a function that retains access to variables from its outer (enclosing) scope even after the outer function has returned. Example: a function inside another function can access the outer function's variables. Closures enable data privacy, partial application, and callback patterns.",
      difficulty: "medium",
      tags: ["javascript"],
      is_top50: true,
    },
    {
      question: "What is the virtual DOM and how does React use it?",
      answer: "The virtual DOM is a lightweight JavaScript representation of the actual DOM. React uses it to optimize updates: when state changes, React creates a new virtual DOM tree, diffs it against the previous one (reconciliation), calculates minimal DOM mutations, and applies them in batch. This avoids expensive direct DOM manipulation.",
      difficulty: "medium",
      tags: ["react"],
      is_top50: true,
    },
    {
      question: "Explain event delegation in JavaScript.",
      answer: "Event delegation leverages event bubbling to handle events at a parent level rather than attaching listeners to each child. A single listener on a parent catches events from all children via `event.target`. Benefits: fewer listeners, works for dynamically added elements, better memory usage.",
      difficulty: "medium",
      tags: ["javascript"],
      is_top50: true,
    },
    {
      question: "What are Web Workers and when would you use them?",
      answer: "Web Workers run JavaScript in background threads separate from the main UI thread. They communicate via postMessage. Use them for CPU-intensive tasks (image processing, large computations, data parsing) that would otherwise block the UI. They don't have DOM access and must be served from the same origin.",
      difficulty: "hard",
      tags: ["javascript", "performance"],
      is_top50: true,
    },
    {
      question: "What are CSS preprocessors and why use them?",
      answer: "CSS preprocessors (Sass, Less, Stylus) extend CSS with features like variables, nesting, mixins, functions, and inheritance. They compile to standard CSS. Benefits: DRY code, easier maintenance, reusable styles, and logical organization. Modern CSS has adopted some of these features natively (CSS custom properties, nesting in CSS).",
      difficulty: "easy",
      tags: ["css"],
      is_top50: true,
    },
  ],
  "backend-engineer": [
    {
      question: "What is an API and how does it work?",
      answer: "An API (Application Programming Interface) defines how software components communicate. REST APIs use HTTP methods (GET, POST, PUT, DELETE) to perform CRUD operations on resources. Clients send requests with headers and body; servers return responses with status codes and data (usually JSON).",
      difficulty: "easy",
      tags: ["api-design"],
      is_top50: true,
    },
    {
      question: "Explain the difference between SQL and NoSQL databases.",
      answer: "SQL databases (PostgreSQL, MySQL) use structured schemas, tables with relationships, and ACID transactions. NoSQL databases (MongoDB, Firebase) offer flexible schemas, horizontal scaling, and eventual consistency. SQL is better for complex queries and data integrity; NoSQL for rapid iteration and large-scale distributed systems.",
      difficulty: "easy",
      tags: ["databases"],
      is_top50: true,
    },
    {
      question: "What is indexing in databases and why is it important?",
      answer: "An index is a data structure (B-tree, hash) that speeds up data retrieval by providing fast lookup paths. Without indexes, queries perform full table scans (O(n)). Indexes make SELECT queries fast but slow down INSERT/UPDATE/DELETE. Common types: primary key index, unique index, composite index, full-text index.",
      difficulty: "medium",
      tags: ["databases"],
      is_top50: true,
    },
    {
      question: "Explain the concept of normalization in databases.",
      answer: "Normalization organizes relational databases to reduce data redundancy and improve integrity. Normal forms: 1NF (atomic columns), 2NF (no partial dependencies), 3NF (no transitive dependencies). Higher normal forms exist but are less common. Trade-off: normalization reduces redundancy but may require more JOINs.",
      difficulty: "medium",
      tags: ["databases"],
      is_top50: true,
    },
    {
      question: "What is JWT and how does authentication work with it?",
      answer: "JWT (JSON Web Token) is a compact, self-contained token format for securely transmitting information. It consists of a header, payload (claims), and signature. For authentication: user logs in → server returns a JWT → client stores it (localStorage/httpOnly cookie) → sends it in Authorization header → server verifies signature.",
      difficulty: "medium",
      tags: ["authentication", "security"],
      is_top50: true,
    },
    {
      question: "Explain the difference between authentication and authorization.",
      answer: "Authentication verifies identity ('who you are') — usually via credentials (password, OAuth, biometrics). Authorization determines access ('what you can do') — checks permissions/roles after authentication. First you authenticate, then you authorize. Example: logging in (authN) vs accessing admin panel (authZ).",
      difficulty: "easy",
      tags: ["security"],
      is_top50: true,
    },
    {
      question: "What are ACID properties in databases?",
      answer: "ACID stands for Atomicity (transactions are all-or-nothing), Consistency (transactions maintain database validity), Isolation (concurrent transactions don't interfere), Durability (committed data persists even after crashes). These properties ensure reliable transaction processing, critical for financial and mission-critical systems.",
      difficulty: "medium",
      tags: ["databases"],
      is_top50: true,
    },
    {
      question: "What is the difference between horizontal and vertical scaling?",
      answer: "Vertical scaling adds more resources (CPU, RAM, disk) to a single machine — simpler but has hardware limits and creates a single point of failure. Horizontal scaling adds more machines to a pool — more complex (load balancers, distributed data) but virtually unlimited and provides fault tolerance. Modern systems favor horizontal scaling.",
      difficulty: "medium",
      tags: ["system-design"],
      is_top50: true,
    },
  ],
  "fullstack-engineer": [
    {
      question: "How does a full-stack application handle CORS?",
      answer: "CORS (Cross-Origin Resource Sharing) is a browser security mechanism that restricts requests from different origins. The server must include specific headers: `Access-Control-Allow-Origin`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`. Browsers send a preflight OPTIONS request for non-simple requests. Solutions: server-side CORS config, reverse proxy, or same-origin deployment.",
      difficulty: "medium",
      tags: ["security", "api-design"],
      is_top50: true,
    },
    {
      question: "What is the role of a reverse proxy in web applications?",
      answer: "A reverse proxy (Nginx, Caddy, HAProxy) sits in front of application servers handling: load balancing (distribute traffic), SSL termination, caching, compression, rate limiting, and serving static files. It improves security by hiding backend servers and provides a single entry point for clients.",
      difficulty: "medium",
      tags: ["devops", "networking"],
      is_top50: true,
    },
    {
      question: "Explain the concept of state management in frontend applications.",
      answer: "State management handles the data that changes over time in a UI. Options: local state (React useState, component-level), global state (Redux, Zustand, Context API), server state (React Query, SWR), URL state (query params), and persisted state (localStorage). Choose based on scope and sharing needs.",
      difficulty: "medium",
      tags: ["react", "architecture"],
      is_top50: true,
    },
    {
      question: "What is the difference between monolithic and microservices architecture?",
      answer: "Monolithic architecture is a single codebase deployed as one unit — simpler to develop and test initially but hard to scale and maintain as it grows. Microservices split functionality into independent services — each with its own database, deployable separately, independently scalable, but introduces distributed system complexity (network latency, data consistency, service discovery).",
      difficulty: "hard",
      tags: ["architecture", "system-design"],
      is_top50: true,
    },
    {
      question: "How do you optimize a web application for performance?",
      answer: "Frontend: lazy loading, code splitting, image optimization, bundling/minification, CDN, caching headers. Backend: database query optimization, connection pooling, caching (Redis), compression, async processing. Full-stack: SSR/SSG, edge functions, performance monitoring (Lighthouse, Web Vitals), reduce waterfall requests.",
      difficulty: "hard",
      tags: ["performance", "optimization"],
      is_top50: true,
    },
    {
      question: "What is a WebSocket and when would you use it?",
      answer: "WebSocket provides full-duplex, persistent communication between client and server over a single TCP connection. Unlike HTTP (request-response), the server can push data to clients at any time. Use cases: real-time chat, live notifications, collaborative editing, gaming, financial tickers. Upgrade from HTTP via the `Upgrade` header.",
      difficulty: "medium",
      tags: ["networking", "real-time"],
      is_top50: true,
    },
    {
      question: "Explain the concept of server-side rendering (SSR) vs client-side rendering (CSR).",
      answer: "CSR loads a minimal HTML shell that renders in the browser via JavaScript — fast initial load but slow time-to-interactive (TTI) and poor SEO. SSR generates HTML on the server per request — better SEO, faster first paint, but higher server load. Next.js offers both: SSR, SSG (static generation), and ISR (incremental static regeneration).",
      difficulty: "medium",
      tags: ["react", "architecture"],
      is_top50: true,
    },
    {
      question: "What are the key considerations when designing a RESTful API?",
      answer: "Consider: resource naming (plural nouns, /users not /getUsers), HTTP methods (GET for read, POST for create, PUT/PATCH for update, DELETE for remove), consistent error responses (status codes + error body), versioning (/v1/users), pagination (offset/limit or cursor-based), authentication (JWT/API keys), rate limiting, and documentation (OpenAPI/Swagger).",
      difficulty: "medium",
      tags: ["api-design"],
      is_top50: true,
    },
  ],
  "devops-engineer": [
    {
      question: "What is CI/CD and why is it important?",
      answer: "CI/CD stands for Continuous Integration/Continuous Deployment. CI automatically builds and tests code on every push to catch bugs early. CD automatically deploys code to production after passing tests. Benefits: faster release cycles, reduced manual errors, consistent processes, rapid feedback, and reliable deployments.",
      difficulty: "easy",
      tags: ["ci-cd"],
      is_top50: true,
    },
    {
      question: "Explain the difference between Docker and virtual machines.",
      answer: "Docker containers share the host OS kernel (lightweight), start in seconds, and have minimal overhead. VMs include a full guest OS per instance (heavyweight), start in minutes, and provide stronger isolation. Containers are better for microservices and scaling; VMs are better when running different OS kernels or requiring stronger security boundaries.",
      difficulty: "medium",
      tags: ["docker", "virtualization"],
      is_top50: true,
    },
    {
      question: "What is Kubernetes and what problem does it solve?",
      answer: "Kubernetes (K8s) is a container orchestration platform that automates deployment, scaling, and management of containerized applications. It solves: service discovery, load balancing, automatic scaling, rolling updates, self-healing (restarting failed containers), storage orchestration, and configuration management. It abstracts away the underlying infrastructure.",
      difficulty: "hard",
      tags: ["kubernetes", "orchestration"],
      is_top50: true,
    },
    {
      question: "What is Infrastructure as Code (IaC)?",
      answer: "IaC manages infrastructure (servers, networks, databases) through code and configuration files rather than manual processes. Tools: Terraform (multi-cloud), AWS CloudFormation, Pulumi, Ansible. Benefits: version control, reproducibility, automation, self-documentation, consistency across environments (dev/staging/prod), and reduced human error.",
      difficulty: "medium",
      tags: ["iac", "automation"],
      is_top50: true,
    },
    {
      question: "Explain the concept of blue-green deployment.",
      answer: "Blue-green deployment maintains two identical environments. Blue is live (production); green has the new version. Once green is ready and tested, the router switches traffic from blue to green. This enables zero-downtime deployments, instant rollback (switch back to blue), and easy validation before full rollout.",
      difficulty: "medium",
      tags: ["deployment", "strategies"],
      is_top50: true,
    },
    {
      question: "What is monitoring and observability in DevOps?",
      answer: "Monitoring collects metrics (CPU, memory, latency, error rates) and alerts on anomalies. Observability goes deeper — understanding system state from outputs (logs, metrics, traces). The three pillars: logs (detailed events), metrics (aggregated numbers), and traces (request flow across services). Tools: Prometheus, Grafana, Datadog, OpenTelemetry.",
      difficulty: "medium",
      tags: ["monitoring", "observability"],
      is_top50: true,
    },
    {
      question: "What is a load balancer and how does it work?",
      answer: "A load balancer distributes incoming traffic across multiple backend servers. Algorithms: round-robin, least connections, IP hash, weighted distribution. It handles health checks (removing unhealthy servers), SSL termination, and can provide session persistence. Types: Layer 4 (transport-level, faster) and Layer 7 (application-level, content-aware).",
      difficulty: "easy",
      tags: ["networking"],
      is_top50: true,
    },
    {
      question: "Explain the concept of 'shift-left' in DevOps.",
      answer: "Shift-left moves testing, security, and quality checks earlier in the development lifecycle (left on the timeline). Instead of finding bugs in production, catch them during development. Practices: unit tests, static code analysis, security scanning in CI, linting, code review. Benefits: cheaper to fix early, faster feedback, higher quality releases.",
      difficulty: "medium",
      tags: ["testing", "best-practices"],
      is_top50: true,
    },
  ],
  "qa-engineer": [
    {
      question: "What is the difference between manual and automated testing?",
      answer: "Manual testing relies on human testers to execute test cases — good for exploratory, usability, and ad-hoc testing. Automated testing uses scripts/tools (Selenium, Cypress, Playwright) to run tests — faster, repeatable, and scalable. Best approach: automate regression, smoke, and data-driven tests; keep manual for UX and exploratory testing.",
      difficulty: "easy",
      tags: ["testing-basics"],
      is_top50: true,
    },
    {
      question: "Explain the difference between unit, integration, and end-to-end testing.",
      answer: "Unit testing tests individual functions/components in isolation. Integration testing verifies that different modules work together (API + database). End-to-end (E2E) testing simulates real user flows across the entire system. The testing pyramid suggests: many unit tests, fewer integration tests, fewest E2E tests.",
      difficulty: "easy",
      tags: ["testing-types"],
      is_top50: true,
    },
    {
      question: "What is the testing pyramid?",
      answer: "The testing pyramid (by Mike Cohn) recommends: Base — many fast unit tests (isolated functions). Middle — fewer integration tests (module interactions). Top — few slow E2E tests (full user flows). This ensures fast feedback from unit tests while E2E tests catch system-level issues. Modern variants include the trophy or honeycomb shapes.",
      difficulty: "easy",
      tags: ["testing-strategy"],
      is_top50: true,
    },
    {
      question: "What is TDD (Test-Driven Development)?",
      answer: "TDD follows a red-green-refactor cycle: 1) Write a failing test (red). 2) Write minimal code to pass it (green). 3) Refactor while keeping tests green. Benefits: ensures test coverage, drives better design, provides documentation, and gives confidence for refactoring. Critics note it can slow initial development.",
      difficulty: "medium",
      tags: ["testing-methodology"],
      is_top50: true,
    },
    {
      question: "What is the difference between black-box and white-box testing?",
      answer: "Black-box testing focuses on inputs and outputs without knowledge of internal code structure — tests functionality from user perspective. White-box testing uses knowledge of internal code to design tests — covers specific paths, branches, and conditions. Gray-box testing combines both approaches.",
      difficulty: "medium",
      tags: ["testing-methodology"],
      is_top50: true,
    },
    {
      question: "What are mocking and stubbing in testing?",
      answer: "Mocking replaces real objects with simulated ones to test behavior (verify interactions). Stubbing provides predefined responses to method calls (controls inputs). Both isolate the unit under test from dependencies (databases, APIs, file systems). Libraries: Jest, Sinon, Mockito. Essential for reliable unit testing.",
      difficulty: "medium",
      tags: ["testing-tools"],
      is_top50: true,
    },
    {
      question: "What is regression testing and why is it important?",
      answer: "Regression testing verifies that new code changes don't break existing functionality. It's critical after bug fixes, feature additions, or refactoring. Automated regression suites provide rapid feedback. Risk-based regression prioritizes critical paths. Without it, software quality degrades over time.",
      difficulty: "easy",
      tags: ["testing-types"],
      is_top50: true,
    },
    {
      question: "What is the Page Object Model (POM) in test automation?",
      answer: "POM is a design pattern where each web page is represented by a class. The class encapsulates page elements (locators) and interactions (methods). Tests use page objects instead of directly manipulating DOM. Benefits: reduces code duplication, centralizes element changes, improves maintainability of test suites.",
      difficulty: "medium",
      tags: ["automation", "design-patterns"],
      is_top50: true,
    },
  ],
};
